In [ ]:
!pip install beautifulsoup4
!pip install requests

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (4.11.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.7.22)

In [ ]:
from bs4 import BeautifulSoup
import requests  #kunai pani url ma scrapping ko lagi request pathaucha
url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')
soup = requests.get(url)
#soup.text   #yo garda url ko sabai source code string format ma aaucha
# so yo string lai xml or lxml ma convert garnu parcha which is the browser readable format
# beautifulsoup ma string related document ma kaam hudaina
soup = BeautifulSoup(soup.text, "lxml") #xml le chai data dherai cha bhaney dhanna sakdaina
soup

<ipython-input-2-1f77b5eb63e4>:3: MarkupResemblesLocatorWarning: The input looks more like a URL than markup. You may want to use an HTTP client like requests to get the document behind the URL, and feed that document to Beautiful Soup.
  url = BeautifulSoup('https://www.worldometers.info/coronavirus/', 'html.parser')

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]--><!--[if IE 9]> <html lang="en" class="ie9"> <![endif]--><!--[if !IE]><!--><html lang="en">
<!--<![endif]-->
<head>
<meta charset="utf-8"/>
<meta content="IE=edge" http-equiv="X-UA-Compatible"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<title>COVID - Coronavirus Statistics - Worldometer</title>
<meta content="Daily and weekly updated statistics tracking the number of COVID-19 cases, recovered, and deaths. Historical data with cumulative charts, graphs, and updates." name="description"/>
<!-- Favicon -->
<link href="/favicon/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
<link href="/favicon/apple-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/>
<link href="/favicon/apple-icon-60x60.png" rel="apple-touch-icon" sizes="60x60"/>
<link href="/favicon/apple-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/>
<link href="/favicon/apple-icon-76x76.png" rel="apple-touch-icon" sizes="76x76"/>
<link href="/favicon/apple-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/>
<link href="/favicon/apple-icon-120x120.png" rel="apple-touch-icon" sizes="120x120"/>
<link href="/favicon/apple-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/>
<link href="/favicon/apple-icon-152x152.png" rel="apple-touch-icon" sizes="152x152"/>
<link href="/favicon/apple-icon-180x180.png" rel="apple-touch-icon" sizes="180x180"/>
<link href="/favicon/android-icon-192x192.png" rel="icon" sizes="192x192" type="image/png"/>
<link href="/favicon/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
<link href="/favicon/favicon-96x96.png" rel="icon" sizes="96x96" type="image/png"/>
<link href="/favicon/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
<link href="/favicon/manifest.json" rel="manifest"/>
<meta content="#ffffff" name="msapplication-TileColor"/>
<meta content="/favicon/ms-icon-144x144.png" name="msapplication-TileImage"/>
<meta content="#ffffff" name="theme-color"/>
<!-- og image -->
<meta content="http://www.worldometers.info/img/worldometers-fb.jpg" property="og:image"/>
<!-- Bootstrap -->
<link href="/css/bootstrap.min.css" rel="stylesheet"/>
<link href="/wm16.css" rel="stylesheet"/>
<!-- font awesome -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"/>
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
<script src="/js/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="/js/ie10-viewport-bug-workaround.js"></script>
<!-- tables
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/s/bs-3.3.5/dt-1.10.10,fh-3.1.0,r-2.0.0/datatables.min.js"></script>


<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.css"/>

<script type="text/javascript" src="https://cdn.datatables.net/s/dt/dt-1.10.10,r-2.0.0/datatables.min.js"></script>
 -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet" type="text/css"/>
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example2').dataTable( {
        "scrollCollapse": true,
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#table3').dataTable( {
        "scrollCollapse": true,
				 "order": [[ 1, 'desc' ]],
		"sDom": '<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
		$.extend( $.fn.dataTable.defaults, {
    responsive: true
} );

	$(document).ready(function() {
    $('#example').dataTable( {
        "scrollCollapse": true,
		"searching": false,

		"sDom": '<"top">rt<"bottom"flp><"clear">',
        "paging":         false
    } );
} );
	</script>
<script class="init" type="text/javascript">
$(document).ready(function() {
	$('#popbycountry').dataTable();
} );
	</script>
<!-- FREESTAR -->
<script data-cfasync="false" type="text/javascript">
  var freestar = freestar || {};
  freestar.hitTime = Date.now();
  freestar.queue = freestar.queue || [];
  freestar.config = freestar.config || {};
  freestar.debug = window.location.search.indexOf('fsdebug') === -1 ? false : true;
  freestar.config.enabled_slots = [];
  !function(a,b){var c=b.getElementsByTagName("script")[0],d=b.createElement("script"),e="https://a.pub.network/worldometers-info";e+=freestar.debug?"/qa/pubfig.min.js":"/pubfig.min.js",d.async=!0,d.src=e,c.parentNode.insertBefore(d,c)}(window,document);
</script>
</head>
<body>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-RWMC0N06EE"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-RWMC0N06EE');
</script>
<!-- Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<!--
<script type="text/javascript" async=true>
(function() {
  var host = 'worldometers.info';
  var element = document.createElement('script');
  var firstScript = document.getElementsByTagName('script')[0];
  var url = 'https://quantcast.mgr.consensu.org'
    .concat('/choice/', 'Pd9JxUkvV0m7q', '/', host, '/choice.js');
  var uspTries = 0;
  var uspTriesLimit = 3;
  element.async = true;
  element.type = 'text/javascript';
  element.src = url;

  firstScript.parentNode.insertBefore(element, firstScript);

  function makeStub() {
    var TCF_LOCATOR_NAME = '__tcfapiLocator';
    var queue = [];
    var win = window;
    var cmpFrame;

    function addFrame() {
      var doc = win.document;
      var otherCMP = !!(win.frames[TCF_LOCATOR_NAME]);

      if (!otherCMP) {
        if (doc.body) {
          var iframe = doc.createElement('iframe');

          iframe.style.cssText = 'display:none';
          iframe.name = TCF_LOCATOR_NAME;
          doc.body.appendChild(iframe);
        } else {
          setTimeout(addFrame, 5);
        }
      }
      return !otherCMP;
    }

    function tcfAPIHandler() {
      var gdprApplies;
      var args = arguments;

      if (!args.length) {
        return queue;
      } else if (args[0] === 'setGdprApplies') {
        if (
          args.length > 3 &&
          args[2] === 2 &&
          typeof args[3] === 'boolean'
        ) {
          gdprApplies = args[3];
          if (typeof args[2] === 'function') {
            args[2]('set', true);
          }
        }
      } else if (args[0] === 'ping') {
        var retr = {
          gdprApplies: gdprApplies,
          cmpLoaded: false,
          cmpStatus: 'stub'
        };

        if (typeof args[2] === 'function') {
          args[2](retr);
        }
      } else {
        queue.push(args);
      }
    }

    function postMessageEventHandler(event) {
      var msgIsString = typeof event.data === 'string';
      var json = {};

      try {
        if (msgIsString) {
          json = JSON.parse(event.data);
        } else {
          json = event.data;
        }
      } catch (ignore) {}

      var payload = json.__tcfapiCall;

      if (payload) {
        window.__tcfapi(
          payload.command,
          payload.version,
          function(retValue, success) {
            var returnMsg = {
              __tcfapiReturn: {
                returnValue: retValue,
                success: success,
                callId: payload.callId
              }
            };
            if (msgIsString) {
              returnMsg = JSON.stringify(returnMsg);
            }
            event.source.postMessage(returnMsg, '*');
          },
          payload.parameter
        );
      }
    }

    while (win) {
      try {
        if (win.frames[TCF_LOCATOR_NAME]) {
          cmpFrame = win;
          break;
        }
      } catch (ignore) {}

      if (win === window.top) {
        break;
      }
      win = win.parent;
    }
    if (!cmpFrame) {
      addFrame();
      win.__tcfapi = tcfAPIHandler;
      win.addEventListener('message', postMessageEventHandler, false);
    }
  };

  makeStub();

  var uspStubFunction = function() {
    var arg = arguments;
    if (typeof window.__uspapi !== uspStubFunction) {
      setTimeout(function() {
        if (typeof window.__uspapi !== 'undefined') {
          window.__uspapi.apply(window.__uspapi, arg);
        }
      }, 500);
    }
  };

  var checkIfUspIsReady = function() {
    uspTries++;
    if (window.__uspapi === uspStubFunction && uspTries < uspTriesLimit) {
      console.warn('USP is not accessible');
    } else {
      clearInterval(uspInterval);
    }
  };

  if (typeof window.__uspapi === 'undefined') {
    window.__uspapi = uspStubFunction;
    var uspInterval = setInterval(checkIfUspIsReady, 6000);
  }
})();
</script>
-->
<!-- End Quantcast Choice. Consent Manager Tag v2.0 (for TCF 2.0) -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-1438574-2', 'auto');
  ga('send', 'pageview');
</script>
<!-- GA wm old (info) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-1438574-30"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1438574-30');
</script>
<!-- GDPR consent -->
<link href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.css" rel="stylesheet" type="text/css"/>
<script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.1.0/cookieconsent.min.js"></script>
<script>
window.addEventListener("load", function(){
window.cookieconsent.initialise({
  "palette": {
    "popup": {
      "background": "#efefef",
      "text": "#404040"
    },
    "button": {
      "background": "#8ec760",
      "text": "#ffffff"
    }
  },
  "theme": "classic",
  "content": {
    "href": "http://www.worldometers.info/policy/"
  }
})});
</script>
<style type="text/css">
    .style1 {
        color: #666666
    }
</style>
<div class="navbar navbar-default">
<div class="container">
<div class="navbar-header">
<div class="logo"><a class="navbar-brand" href="/"><img border="0" src="/img/worldometers-logo.gif" title="Worldometer"/></a></div>
<button class="navbar-toggle" data-target="#navbar-main" data-toggle="collapse" type="button">
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
</div>
<div class="navbar-collapse collapse" id="navbar-main">
<ul class="nav navbar-nav">
<li><a href="/coronavirus/">Coronavirus</a></li>
<li><a href="/population/">Population</a></li>
</ul>
</div>
</div>
</div>
<!-- MAIN -->
<div class="container">
<!-- TOP AD -->
<div class="row">
<div style="text-align:left; margin-bottom:10px">
<script async="" src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- wm_top970 -->
<ins class="adsbygoogle" data-ad-client="ca-pub-3701697624350410" data-ad-slot="3287840995" style="display:inline-block;width:970px;height:90px"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
</div>
<!-- TOP AD -->
<!-- MAIN  -->
<!-- CENTER -->
<div class="row"> <div class="col-md-8">
<!-- *** CONTENT A *** -->
<div class="content-inner">
<style>
    .number-table {
        font-size: 20px;
        font-weight: bold
    }

    .number-table-main {
        font-size: 24px;
        font-weight: bold
    }
</style>
<!-- charts -->
<script src="/js/highcharts.js"></script>
<style type="text/css">
    .source {}

    .style2 {
        color: #FF0000
    }

    .style4 {
        color: #FF0000;
        font-weight: bold;
    }

    .style6 {
        font-size: 12px;
        color: #bbb;
        font-weight: bold;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source1 {
        font-size: 12px;
        color: #bbb;
    }

    .source11 {
        font-size: 12px;
        color: #bbb;
    }

    .source111 {}

    .source1111 {
        font-size: 12px;
        color: #bbb;
    }


    .new_badge {

        position: absolute;
        font-size: 12px;
        top: -5px;
        right: -26px;
        background-color: #8ACA2B;
        color: white;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }

    .new_badge_link {

        background-color: #8ACA2B;
        color: white !important;
        padding-left: 4px;
        padding-right: 4px;
        padding-top: 2px;
        padding-bottom: 2px;
        border-radius: 4px;
        ;
    }
</style>
<div class="label-counter" id="page-top">COVID-19 Coronavirus Pandemic</div>
<div style="font-size:13px; color:#999; margin-top:5px; text-align:center">Last updated: September 10, 2023, 01:33 GMT</div>
<div style="margin-top:20px; text-align:center; font-size:14px"><a class="new_badge_link" href="/coronavirus/weekly-trends/" style="display: inline-block; position:relative;">Weekly Trends</a> - <a href="/coronavirus/worldwide-graphs/">Graphs</a> - <a href="#countries">Countries</a> - <a href="#news">News</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Coronavirus Cases:</h1>
<div class="maincounter-number">
<span style="color:#aaa">695,104,239        </span>
</div>
</div>
<div style="text-align:center "><a href="#countries">view by country</a></div>
<div id="maincounter-wrap" style="margin-top:15px">
<h1>Deaths:</h1>
<div class="maincounter-number">
<span>6,914,374</span>
</div>
</div>
<div id="maincounter-wrap" style="margin-top:15px;">
<h1>Recovered:</h1>
<div class="maincounter-number" style="color:#8ACA2B ">
<span>667,017,478</span>
</div>
</div>
<div style="margin-top:50px;"></div>
<!-- START -->
<style>
    .panel_flip {
        position: relative;
        height: 100%;
    }

    .panel_front {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_back {

        height: inherit;
        position: absolute;
        top: 0;
        -webkit-transform: rotateY(-180deg);
        -moz-transform: rotateY(-180deg);
        -webkit-transform-style: preserve-3d;
        -moz-transform-style: preserve-3d;
        -webkit-backface-visibility: hidden;
        -moz-backface-visibility: hidden;
        -webkit-transition: all .4s ease-in-out;
        -moz-transition: all .4s ease-in-out;
        -ms-transition: all .4s ease-in-out;
        -o-transition: all .4s ease-in-out;
        transition: all .4s ease-in-out;
    }

    .panel_flip.flip .panel_front {

        z-index: 900;
        -webkit-transform: rotateY(180deg);
        -moz-transform: rotateY(180deg);
    }

    .panel_flip.flip .panel_back {

        z-index: 1000;
        -webkit-transform: rotateX(0deg) rotateY(0deg);
        -moz-transform: rotateX(0deg) rotateY(0deg);
    }

    .collapse_button {

        position: absolute;
        right: 10px;
        pointer-events: none;
        color: #70757a !important;
        height: 24px;
        width: 24px;
        line-height: 24px;
    }

    .collapse_button svg {
        display: block;
        height: 100%;
        width: 100%;
        fill: currentColor;
    }

    .rotate_180 {

        transform: rotate(180deg);
    }

    .panel_clickable {

        cursor: pointer;
    }
</style>
<script>
    var do_not_slide = false;
    $(function() {

        $('.flip_cases_front').on('click', function() {


            $(this).parent().parent().addClass('flip');
        });

        $('.flip_cases_back').on('click', function() {


            $(this).parent().parent().removeClass('flip');
        });


        $('.collapse').on('show.bs.collapse', function(el) {


            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.addClass('rotate_180');

            if (do_not_slide) {

                return;
            }

            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('show');
            } else {

                $('#panel_active').collapse('show');
            }

            do_not_slide = false;
        });

        $('.collapse').on('hide.bs.collapse', function(el) {

            var collapse_button = $(el.target).parent().find('.collapse_button');
            collapse_button.removeClass('rotate_180');


            if (do_not_slide) {

                return;
            }


            do_not_slide = true;
            if ($(el.target).attr('id') == 'panel_active') {

                $('#panel_closed').collapse('hide');
            } else {

                $('#panel_active').collapse('hide');
            }

            do_not_slide = false;

        });



    });
</script>
<div class="col-md-6">
<div class="panel panel-default">
<div aria-controls="panel_active" aria-expanded="false" class="panel_clickable panel-heading" data-toggle="collapse" href="#panel_active" style="text-align:center;position:relative;">
<span class="panel-title" style="font-size:18px; text-transform:uppercase; font-weight:100">
                    Active Cases
                </span>
<span class="collapse_button"><svg focusable="false" viewbox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
<path d="M7.41 8.59L12 13.17l4.59-4.58L18 10l-6 6-6-6 1.41-1.41z"></path>
</svg></span>
</div>
<div class="collapse" id="panel_active">
<div class="panel-body" style="text-align:center;min-height:220px;">
<div class="panel_flip">
<div class="panel_front" style="width:100%;height:100%;">
<div class="number-table-main">21,172,387</div>
<div style="font-size:13.5px">Currently Infected Patients</div>
<div style="padding-top:20px;position:relative;text-align:center; ">
<div style="float:left; text-align:center">
<span class="number-table" style="color:#8080FF">21,134,570</span> (<strong>99.8</strong>%)

                                    <div style="font-size:13px">in Mild Condition</div><br/>
</div>
<div style="float:right; text-align:center"><span class="number-table" style="color:red ">37,817</span> (<strong>0.2</strong>%)

In [ ]:
table_code = soup.table # tag ko naam table bhako bhayera table liyeko
table_code # aba table ko code matra lincha

<table class="table table-bordered table-hover main_table_countries" id="main_table_countries_today" style="width:100%;margin-top: 0px !important;display:none;">
<thead>
<tr>
<th width="1%">#</th>
<th width="100">Country,<br/>Other</th>
<th width="20">Total<br/>Cases</th>
<th width="30">New<br/>Cases</th>
<th width="30">Total<br/>Deaths</th>
<th width="30">New<br/>Deaths</th>
<th width="30">Total<br/>Recovered</th>
<th width="30">New<br/>Recovered</th>
<th width="30">Active<br/>Cases</th>
<th width="30">Serious,<br/>Critical</th>
<th width="30">Tot Cases/<br/>1M pop</th>
<th width="30">Deaths/<br/>1M pop</th>
<th width="30">Total<br/>Tests</th>
<th width="30">Tests/<br/>
<nobr>1M pop</nobr>
</th>
<th width="30">Population</th>
<th style="display:none" width="30">Continent</th>
<th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
<th width="30">New Cases/1M pop</th>
<th width="30">New Deaths/1M pop</th>
<th width="30">Active Cases/1M pop</th>
</tr>
</thead>
<tbody>
<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>North America</nobr>
</td>
<td>128,016,618</td>
<td></td>
<td>1,644,500</td>
<td></td>
<td>123,641,182</td>
<td>+240</td>
<td>2,730,936</td>
<td>6,528</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="North America" style="display:none;">North America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Asia</nobr>
</td>
<td>220,719,478</td>
<td></td>
<td>1,549,618</td>
<td></td>
<td>204,263,828</td>
<td>+48,630</td>
<td>14,906,032</td>
<td>15,143</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Asia" style="display:none;">Asia</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Europe</nobr>
</td>
<td>249,919,159</td>
<td></td>
<td>2,070,549</td>
<td></td>
<td>246,007,112</td>
<td>+1,207</td>
<td>1,841,498</td>
<td>5,481</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Europe" style="display:none;">Europe</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="South America" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>South America</nobr>
</td>
<td>68,975,740</td>
<td></td>
<td>1,360,574</td>
<td></td>
<td>66,515,862</td>
<td></td>
<td>1,099,304</td>
<td>10,069</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="South America" style="display:none;">South America</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Oceania</nobr>
</td>
<td>14,635,305</td>
<td></td>
<td>30,289</td>
<td></td>
<td>14,500,555</td>
<td></td>
<td>104,461</td>
<td>49</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr>Africa</nobr>
</td>
<td>12,837,218</td>
<td></td>
<td>258,829</td>
<td></td>
<td>12,088,233</td>
<td></td>
<td>490,156</td>
<td>547</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="Africa" style="display:none;">Africa</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world row_continent" data-continent="" style="display: none">
<td></td>
<td style="text-align:left;">
<nobr></nobr>
</td>
<td>721</td>
<td></td>
<td>15</td>
<td></td>
<td>706</td>
<td></td>
<td>0</td>
<td>0</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td data-continent="" style="display:none;"></td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="total_row_world">
<td></td>
<td style="text-align:left;">World</td>
<td>695,104,239</td>
<td>0</td>
<td>6,914,374</td>
<td>0</td>
<td>667,017,478</td>
<td>+49,638</td>
<td>21,172,387</td>
<td>37,817</td>
<td>89,175</td>
<td>887.0</td>
<td></td>
<td></td>
<td></td>
<td data-continent="all" style="display:none">All</td>
<!-- 1 Case every X -->
<td>
</td>
<!-- 1 Death every X -->
<td></td>
<!-- 1 test every X -->
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
<td style="font-weight: bold; text-align:right">108,292,767</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">1,174,578                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">106,093,952</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">1,024,237</td>
<td style="font-weight: bold; text-align:right">1,362</td>
<td style="font-weight: bold; text-align:right">323,450</td>
<td style="font-weight: bold; text-align:right">3,508</td>
<td style="font-weight: bold; text-align:right">1,186,093,362</td>
<td style="font-weight: bold; text-align:right">3,542,636</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
<td data-continent="North America" style="display:none">North America</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>285</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,059</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
<td style="font-weight: bold; text-align:right">44,997,642</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">531,930                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">44,465,138</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">574</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">31,990</td>
<td style="font-weight: bold; text-align:right">378</td>
<td style="font-weight: bold; text-align:right">930,797,975</td>
<td style="font-weight: bold; text-align:right">661,721</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>31</td><td>2,644</td><td>2</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">0.4</td>
</tr>
<tr style="background-color:#F0F0F0">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
<td style="font-weight: bold; text-align:right">40,138,560</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">167,642                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">0</td>
<td style="font-weight: bold; text-align:right">869</td>
<td style="font-weight: bold; text-align:right">612,013</td>
<td style="font-weight: bold; text-align:right">2,556</td>
<td style="font-weight: bold; text-align:right">271,490,188</td>
<td style="font-weight: bold; text-align:right">4,139,547</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>391</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
<td style="font-weight: bold; text-align:right">38,428,685</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">174,352                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">38,240,600</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">13,733</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">458,119</td>
<td style="font-weight: bold; text-align:right">2,078</td>
<td style="font-weight: bold; text-align:right">122,332,384</td>
<td style="font-weight: bold; text-align:right">1,458,359</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>481</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">164</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
<td style="font-weight: bold; text-align:right">37,783,855</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">705,313                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">36,249,161</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">829,381</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">175,450</td>
<td style="font-weight: bold; text-align:right">3,275</td>
<td style="font-weight: bold; text-align:right">63,776,166</td>
<td style="font-weight: bold; text-align:right">296,146</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
<td data-continent="South America" style="display:none">South America</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>305</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">3,851</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
<td style="font-weight: bold; text-align:right">34,571,873</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">35,934                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,239,297</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+48,162</td>
<td style="text-align:right;font-weight:bold;">296,642</td>
<td style="font-weight: bold; text-align:right">231</td>
<td style="font-weight: bold; text-align:right">673,523</td>
<td style="font-weight: bold; text-align:right">700</td>
<td style="font-weight: bold; text-align:right">15,804,065</td>
<td style="font-weight: bold; text-align:right">307,892</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>1</td><td>1,428</td><td>3</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">5,779</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
<td style="font-weight: bold; text-align:right">33,803,572</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">74,694                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right;">N/A</td>
<td style="text-align:right;font-weight:bold;">N/A</td>
<td style="font-weight: bold; text-align:right">83</td>
<td style="font-weight: bold; text-align:right">269,169</td>
<td style="font-weight: bold; text-align:right">595</td>
<td style="font-weight: bold; text-align:right">100,414,883</td>
<td style="font-weight: bold; text-align:right">799,578</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
<td data-continent="Asia" style="display:none">Asia</td>
<!-- 1 Case/Death/Test every X -->
<td>4</td><td>1,681</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">95,582</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
<td style="font-weight: bold; text-align:right">25,977,012</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">191,370                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">25,653,509</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">132,133</td>
<td style="font-weight: bold; text-align:right">52</td>
<td style="font-weight: bold; text-align:right">431,062</td>
<td style="font-weight: bold; text-align:right">3,176</td>
<td style="font-weight: bold; text-align:right">291,154,734</td>
<td style="font-weight: bold; text-align:right">4,831,420</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>2</td><td>315</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">2,193</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
<td style="font-weight: bold; text-align:right">24,688,073</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">228,924                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,441,574</span></td>
<td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,121</td>
<td style="text-align:right;font-weight:bold;">17,575</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">360,421</td>
<td style="font-weight: bold; text-align:right">3,342</td>
<td style="font-weight: bold; text-align:right">522,526,476</td>
<td style="font-weight: bold; text-align:right">7,628,357</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>3</td><td>299</td><td>0</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">257</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
<td style="font-weight: bold; text-align:right">22,995,765</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="font-weight: bold; text-align:right;">399,999                                </td>
<td style="font-weight: bold;
                                    text-align:right;"></td>
<td style="font-weight: bold; text-align:right">22,446,519</td>
<td style="font-weight: bold; text-align:right;"></td>
<td style="text-align:right;font-weight:bold;">149,247</td>
<td style="font-weight: bold; text-align:right">N/A</td>
<td style="font-weight: bold; text-align:right">157,715</td>
<td style="font-weight: bold; text-align:right">2,743</td>
<td style="font-weight: bold; text-align:right">273,400,000</td>
<td style="font-weight: bold; text-align:right">1,875,095</td>
<td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
<td data-continent="Europe" style="display:none">Europe</td>
<!-- 1 Case/Death/Test every X -->
<td>6</td><td>365</td><td>1</td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right"></td>
<td style="font-weight: bold; text-align:right">1,024</td>
</tr>
<tr style="">
<td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
<td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/turkey/">Turkey</a></td>

In [ ]:
tags = table_code.find_all('tr')
tags

[<tr>
 <th width="1%">#</th>
 <th width="100">Country,<br/>Other</th>
 <th width="20">Total<br/>Cases</th>
 <th width="30">New<br/>Cases</th>
 <th width="30">Total<br/>Deaths</th>
 <th width="30">New<br/>Deaths</th>
 <th width="30">Total<br/>Recovered</th>
 <th width="30">New<br/>Recovered</th>
 <th width="30">Active<br/>Cases</th>
 <th width="30">Serious,<br/>Critical</th>
 <th width="30">Tot Cases/<br/>1M pop</th>
 <th width="30">Deaths/<br/>1M pop</th>
 <th width="30">Total<br/>Tests</th>
 <th width="30">Tests/<br/>
 <nobr>1M pop</nobr>
 </th>
 <th width="30">Population</th>
 <th style="display:none" width="30">Continent</th>
 <th width="30">1 Case<br/>every X ppl</th><th width="30">1 Death<br/>every X ppl</th><th width="30">1 Test<br/>every X ppl</th>
 <th width="30">New Cases/1M pop</th>
 <th width="30">New Deaths/1M pop</th>
 <th width="30">Active Cases/1M pop</th>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>128,016,618</td>
 <td></td>
 <td>1,644,500</td>
 <td></td>
 <td>123,641,182</td>
 <td>+240</td>
 <td>2,730,936</td>
 <td>6,528</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>220,719,478</td>
 <td></td>
 <td>1,549,618</td>
 <td></td>
 <td>204,263,828</td>
 <td>+48,630</td>
 <td>14,906,032</td>
 <td>15,143</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>249,919,159</td>
 <td></td>
 <td>2,070,549</td>
 <td></td>
 <td>246,007,112</td>
 <td>+1,207</td>
 <td>1,841,498</td>
 <td>5,481</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>68,975,740</td>
 <td></td>
 <td>1,360,574</td>
 <td></td>
 <td>66,515,862</td>
 <td></td>
 <td>1,099,304</td>
 <td>10,069</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>14,635,305</td>
 <td></td>
 <td>30,289</td>
 <td></td>
 <td>14,500,555</td>
 <td></td>
 <td>104,461</td>
 <td>49</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>12,837,218</td>
 <td></td>
 <td>258,829</td>
 <td></td>
 <td>12,088,233</td>
 <td></td>
 <td>490,156</td>
 <td>547</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>706</td>
 <td></td>
 <td>0</td>
 <td>0</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>695,104,239</td>
 <td>0</td>
 <td>6,914,374</td>
 <td>0</td>
 <td>667,017,478</td>
 <td>+49,638</td>
 <td>21,172,387</td>
 <td>37,817</td>
 <td>89,175</td>
 <td>887.0</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <!-- 1 Case every X -->
 <td>
 </td>
 <!-- 1 Death every X -->
 <td></td>
 <!-- 1 test every X -->
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">108,292,767</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">1,174,578                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">106,093,952</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">1,024,237</td>
 <td style="font-weight: bold; text-align:right">1,362</td>
 <td style="font-weight: bold; text-align:right">323,450</td>
 <td style="font-weight: bold; text-align:right">3,508</td>
 <td style="font-weight: bold; text-align:right">1,186,093,362</td>
 <td style="font-weight: bold; text-align:right">3,542,636</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">334,805,269</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>285</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,059</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">44,997,642</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">531,930                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">44,465,138</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">574</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">31,990</td>
 <td style="font-weight: bold; text-align:right">378</td>
 <td style="font-weight: bold; text-align:right">930,797,975</td>
 <td style="font-weight: bold; text-align:right">661,721</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,406,631,776</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>31</td><td>2,644</td><td>2</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">0.4</td>
 </tr>,
 <tr style="background-color:#F0F0F0">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">40,138,560</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">167,642                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">39,970,918</span></td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">0</td>
 <td style="font-weight: bold; text-align:right">869</td>
 <td style="font-weight: bold; text-align:right">612,013</td>
 <td style="font-weight: bold; text-align:right">2,556</td>
 <td style="font-weight: bold; text-align:right">271,490,188</td>
 <td style="font-weight: bold; text-align:right">4,139,547</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,584,518</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>391</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/germany/">Germany</a></td>
 <td style="font-weight: bold; text-align:right">38,428,685</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">174,352                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">38,240,600</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">13,733</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">458,119</td>
 <td style="font-weight: bold; text-align:right">2,078</td>
 <td style="font-weight: bold; text-align:right">122,332,384</td>
 <td style="font-weight: bold; text-align:right">1,458,359</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/germany-population/">83,883,596</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>481</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">164</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">37,783,855</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">705,313                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">36,249,161</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">829,381</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">175,450</td>
 <td style="font-weight: bold; text-align:right">3,275</td>
 <td style="font-weight: bold; text-align:right">63,776,166</td>
 <td style="font-weight: bold; text-align:right">296,146</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">215,353,593</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>305</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">3,851</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-korea/">S. Korea</a></td>
 <td style="font-weight: bold; text-align:right">34,571,873</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">35,934                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">34,239,297</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+48,162</td>
 <td style="text-align:right;font-weight:bold;">296,642</td>
 <td style="font-weight: bold; text-align:right">231</td>
 <td style="font-weight: bold; text-align:right">673,523</td>
 <td style="font-weight: bold; text-align:right">700</td>
 <td style="font-weight: bold; text-align:right">15,804,065</td>
 <td style="font-weight: bold; text-align:right">307,892</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-korea-population/">51,329,899</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>1</td><td>1,428</td><td>3</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">5,779</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/japan/">Japan</a></td>
 <td style="font-weight: bold; text-align:right">33,803,572</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">74,694                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">83</td>
 <td style="font-weight: bold; text-align:right">269,169</td>
 <td style="font-weight: bold; text-align:right">595</td>
 <td style="font-weight: bold; text-align:right">100,414,883</td>
 <td style="font-weight: bold; text-align:right">799,578</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/japan-population/">125,584,838</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <!-- 1 Case/Death/Test every X -->
 <td>4</td><td>1,681</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">95,582</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/italy/">Italy</a></td>
 <td style="font-weight: bold; text-align:right">25,977,012</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">191,370                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">25,653,509</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">132,133</td>
 <td style="font-weight: bold; text-align:right">52</td>
 <td style="font-weight: bold; text-align:right">431,062</td>
 <td style="font-weight: bold; text-align:right">3,176</td>
 <td style="font-weight: bold; text-align:right">291,154,734</td>
 <td style="font-weight: bold; text-align:right">4,831,420</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/italy-population/">60,262,770</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>2</td><td>315</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">2,193</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">24,688,073</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">228,924                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right"><span style="color:grey; font-style: italic;">24,441,574</span></td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+1,121</td>
 <td style="text-align:right;font-weight:bold;">17,575</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">360,421</td>
 <td style="font-weight: bold; text-align:right">3,342</td>
 <td style="font-weight: bold; text-align:right">522,526,476</td>
 <td style="font-weight: bold; text-align:right">7,628,357</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/uk-population/">68,497,907</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>3</td><td>299</td><td>0</td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right"></td>
 <td style="font-weight: bold; text-align:right">257</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">22,995,765</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">399,999                                </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">22,446,519</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">149,247</td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right">157,715</td>
 <td style="font-weight: bold; text-align:right">2,743</td>
 <td style="font-weight: bold; text-align:right">273,400,000</td>
 <td style="font-weight: bold; text-align:right">1,875,095</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,805,947</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <!-- 1 Case/Death/Test every X -->
 <td>6</td><td>365</td><td>1</td>
 <td style="font-weight: bold; text-align:right"></td>

In [ ]:
data = []
for tag in tags:
    y = tag.text.split('\n')  #tag.text le chai html content lidaina
    #tag bhitra bhako data matra aaucha
    #text chai hamle html content hatayera data matra lina ko lagi use gareko
    if y[1] != "":
        data.append(y[1:])

data

#.split() le string lai \n ko basis ma list ma change gardincha

[['#',
  'Country,Other',
  'TotalCases',
  'NewCases',
  'TotalDeaths',
  'NewDeaths',
  'TotalRecovered',
  'NewRecovered',
  'ActiveCases',
  'Serious,Critical',
  'Tot\xa0Cases/1M pop',
  'Deaths/1M pop',
  'TotalTests',
  'Tests/',
  '1M pop',
  '',
  'Population',
  'Continent',
  '1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl',
  'New Cases/1M pop',
  'New Deaths/1M pop',
  'Active Cases/1M pop',
  ''],
 ['1',
  'USA',
  '108,292,767',
  '',
  '1,174,578                                ',
  '',
  '106,093,952',
  '',
  '1,024,237',
  '1,362',
  '323,450',
  '3,508',
  '1,186,093,362',
  '3,542,636',
  '334,805,269 ',
  'North America',
  '',
  '32850',
  '',
  '',
  '3,059',
  ''],
 ['2',
  'India',
  '44,997,642',
  '',
  '531,930                                ',
  '',
  '44,465,138',
  '',
  '574',
  'N/A',
  '31,990',
  '378',
  '930,797,975',
  '661,721',
  '1,406,631,776 ',
  'Asia',
  '',
  '312,6442',
  '',
  '',
  '0.4',
  ''],
 ['3',
  'France',
  '40,138,560',
  '',
  '167,642                                ',
  '',
  '39,970,918',
  '',
  '0',
  '869',
  '612,013',
  '2,556',
  '271,490,188',
  '4,139,547',
  '65,584,518 ',
  'Europe',
  '',
  '23910',
  '',
  '',
  '',
  ''],
 ['4',
  'Germany',
  '38,428,685',
  '',
  '174,352                                ',
  '',
  '38,240,600',
  '',
  '13,733',
  'N/A',
  '458,119',
  '2,078',
  '122,332,384',
  '1,458,359',
  '83,883,596 ',
  'Europe',
  '',
  '24811',
  '',
  '',
  '164',
  ''],
 ['5',
  'Brazil',
  '37,783,855',
  '',
  '705,313                                ',
  '',
  '36,249,161',
  '',
  '829,381',
  'N/A',
  '175,450',
  '3,275',
  '63,776,166',
  '296,146',
  '215,353,593 ',
  'South America',
  '',
  '63053',
  '',
  '',
  '3,851',
  ''],
 ['6',
  'S. Korea',
  '34,571,873',
  '',
  '35,934                                ',
  '',
  '34,239,297',
  '+48,162',
  '296,642',
  '231',
  '673,523',
  '700',
  '15,804,065',
  '307,892',
  '51,329,899 ',
  'Asia',
  '',
  '11,4283',
  '',
  '',
  '5,779',
  ''],
 ['7',
  'Japan',
  '33,803,572',
  '',
  '74,694                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '83',
  '269,169',
  '595',
  '100,414,883',
  '799,578',
  '125,584,838 ',
  'Asia',
  '',
  '41,6811',
  '',
  '',
  '95,582',
  ''],
 ['8',
  'Italy',
  '25,977,012',
  '',
  '191,370                                ',
  '',
  '25,653,509',
  '',
  '132,133',
  '52',
  '431,062',
  '3,176',
  '291,154,734',
  '4,831,420',
  '60,262,770 ',
  'Europe',
  '',
  '23150',
  '',
  '',
  '2,193',
  ''],
 ['9',
  'UK',
  '24,688,073',
  '',
  '228,924                                ',
  '',
  '24,441,574',
  '+1,121',
  '17,575',
  'N/A',
  '360,421',
  '3,342',
  '522,526,476',
  '7,628,357',
  '68,497,907 ',
  'Europe',
  '',
  '32990',
  '',
  '',
  '257',
  ''],
 ['10',
  'Russia',
  '22,995,765',
  '',
  '399,999                                ',
  '',
  '22,446,519',
  '',
  '149,247',
  'N/A',
  '157,715',
  '2,743',
  '273,400,000',
  '1,875,095',
  '145,805,947 ',
  'Europe',
  '',
  '63651',
  '',
  '',
  '1,024',
  ''],
 ['11',
  'Turkey',
  '17,232,066',
  '',
  '102,174                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '',
  '201,399',
  '1,194',
  '162,743,369',
  '1,902,052',
  '85,561,976 ',
  'Asia',
  '',
  '58371',
  '',
  '',
  '4,024',
  ''],
 ['12',
  'Spain',
  '13,914,811',
  '',
  '121,760                                ',
  '',
  '13,762,417',
  '',
  '30,634',
  '231',
  '297,840',
  '2,606',
  '471,036,328',
  '10,082,298',
  '46,719,142 ',
  'Europe',
  '',
  '33840',
  '',
  '',
  '656',
  ''],
 ['13',
  'Australia',
  '11,758,693',
  '',
  '22,687                                ',
  '',
  '11,731,218',
  '',
  '4,788',
  '21',
  '451,064',
  '870',
  '81,916,639',
  '3,142,326',
  '26,068,792 ',
  'Australia/Oceania',
  '',
  '21,1490',
  '',
  '',
  '184',
  ''],
 ['14',
  'Vietnam',
  '11,623,182',
  '',
  '43,206                                ',
  '',
  '10,640,624',
  '',
  '939,352',
  '',
  '117,461',
  '437',
  '85,826,548',
  '867,342',
  '98,953,541 ',
  'Asia',
  '',
  '92,2901',
  '',
  '',
  '9,493',
  ''],
 ['15',
  'Taiwan',
  '10,241,520',
  '',
  '19,005                                ',
  '',
  '10,222,515',
  '',
  '0',
  '',
  '428,720',
  '796',
  '30,742,304',
  '1,286,903',
  '23,888,595 ',
  'Asia',
  '',
  '21,2571',
  '',
  '',
  '',
  ''],
 ['16',
  'Argentina',
  '10,064,948',
  '',
  '130,576                                ',
  '',
  '9,931,163',
  '',
  '3,209',
  '363',
  '218,755',
  '2,838',
  '35,716,069',
  '776,264',
  '46,010,234 ',
  'South America',
  '',
  '53521',
  '',
  '',
  '70',
  ''],
 ['17',
  'Netherlands',
  '8,610,372',
  '',
  '22,992                                ',
  '',
  '8,587,380',
  '',
  '0',
  '53',
  '500,270',
  '1,336',
  '25,984,435',
  '1,509,718',
  '17,211,447 ',
  'Europe',
  '',
  '27491',
  '',
  '',
  '',
  ''],
 ['18',
  'Mexico',
  '7,633,355',
  '',
  '334,336                                ',
  '',
  '6,885,378',
  '',
  '413,641',
  'N/A',
  '58,021',
  '2,541',
  '20,013,810',
  '152,124',
  '131,562,772 ',
  'North America',
  '',
  '173947',
  '',
  '',
  '3,144',
  ''],
 ['19',
  'Iran',
  '7,613,757',
  '',
  '146,329                                ',
  '',
  '7,374,684',
  '',
  '92,744',
  '18',
  '88,509',
  '1,701',
  '56,934,517',
  '661,854',
  '86,022,837 ',
  'Asia',
  '',
  '115882',
  '',
  '',
  '1,078',
  ''],
 ['20',
  'Indonesia',
  '6,813,287',
  '',
  '161,918                                ',
  '',
  '6,646,676',
  '',
  '4,693',
  'N/A',
  '24,409',
  '580',
  '114,158,919',
  '408,975',
  '279,134,505 ',
  'Asia',
  '',
  '411,7242',
  '',
  '',
  '17',
  ''],
 ['21',
  'Poland',
  '6,519,692',
  '',
  '119,642                                ',
  '',
  '5,335,940',
  '',
  '1,064,110',
  '53',
  '172,754',
  '3,170',
  '38,828,396',
  '1,028,845',
  '37,739,785 ',
  'Europe',
  '',
  '63151',
  '',
  '',
  '28,196',
  ''],
 ['22',
  'Colombia',
  '6,378,000',
  '',
  '142,961                                ',
  '',
  '6,190,683',
  '',
  '44,356',
  '342',
  '123,814',
  '2,775',
  '36,951,507',
  '717,327',
  '51,512,762 ',
  'South America',
  '',
  '83601',
  '',
  '',
  '861',
  ''],
 ['23',
  'Greece',
  '6,101,379',
  '',
  '37,089                                ',
  '',
  '6,064,290',
  '',
  '0',
  '115',
  '591,412',
  '3,595',
  '102,228,365',
  '9,909,078',
  '10,316,637 ',
  'Europe',
  '',
  '22780',
  '',
  '',
  '',
  ''],
 ['24',
  'Austria',
  '6,081,287',
  '',
  '22,542                                ',
  '',
  '6,054,934',
  '',
  '3,811',
  '14',
  '670,727',
  '2,486',
  '211,273,524',
  '23,302,116',
  '9,066,710 ',
  'Europe',
  '',
  '14020',
  '',
  '',
  '420',
  ''],
 ['25',
  'Portugal',
  '5,610,180',
  '',
  '27,247                                ',
  '',
  '5,573,906',
  '',
  '9,027',
  '61',
  '553,241',
  '2,687',
  '46,139,518',
  '4,549,993',
  '10,140,570 ',
  'Europe',
  '',
  '23720',
  '',
  '',
  '890',
  ''],
 ['26',
  'Ukraine',
  '5,557,995',
  '',
  '112,418                                ',
  '',
  '5,445,577',
  '',
  '0',
  '',
  '128,681',
  '2,603',
  '32,603,805',
  '754,855',
  '43,192,122 ',
  'Europe',
  '',
  '83841',
  '',
  '',
  '',
  ''],
 ['27',
  'Chile',
  '5,291,598',
  '',
  '64,497                                ',
  '',
  '5,227,013',
  '',
  '88',
  '1',
  '274,885',
  '3,350',
  '49,979,167',
  '2,596,294',
  '19,250,195 ',
  'South America',
  '',
  '42980',
  '',
  '',
  '5',
  ''],
 ['28',
  'Malaysia',
  '5,123,801',
  '',
  '37,165                                ',
  '',
  '5,074,097',
  '',
  '12,539',
  '4',
  '154,419',
  '1,120',
  '68,437,185',
  '2,062,537',
  '33,181,072 ',
  'Asia',
  '',
  '68930',
  '',
  '',
  '378',
  ''],
 ['29',
  'Israel',
  '4,834,948',
  '',
  '12,645                                ',
  '',
  '4,798,473',
  '',
  '23,830',
  '21',
  '518,437',
  '1,356',
  '41,373,364',
  '4,436,346',
  '9,326,000 ',
  'Asia',
  '',
  '27380',
  '',
  '',
  '2,555',
  ''],
 ['30',
  'Belgium',
  '4,809,688',
  '',
  '34,376                                ',
  '',
  '4,769,079',
  '',
  '6,233',
  '43',
  '412,202',
  '2,946',
  '37,018,657',
  '3,172,590',
  '11,668,278 ',
  'Europe',
  '',
  '23390',
  '',
  '',
  '534',
  ''],
 ['31',
  'DPRK',
  '4,772,813',
  '',
  '74                                ',
  '',
  '4,772,739',
  '',
  '0',
  '',
  '183,636',
  '3',
  '',
  '',
  '25,990,679 ',
  'Asia',
  '',
  '5351,225',
  '',
  '',
  '',
  ''],
 ['32',
  'Thailand',
  '4,756,593',
  '',
  '34,465                                ',
  '',
  '4,692,636',
  '',
  '29,492',
  'N/A',
  '67,875',
  '492',
  '17,270,775',
  '246,450',
  '70,078,203 ',
  'Asia',
  '',
  '152,0334',
  '',
  '',
  '421',
  ''],
 ['33',
  'Canada',
  '4,710,662',
  '',
  '53,419                                ',
  '',
  '4,647,327',
  '+240',
  '9,916',
  '99',
  '122,710',
  '1,392',
  '66,366,504',
  '1,728,816',
  '38,388,419 ',
  'North America',
  '',
  '87191',
  '',
  '',
  '258',
  ''],
 ['34',
  'Czechia',
  '4,645,345',
  '',
  '42,825                                ',
  '',
  '4,601,362',
  '',
  '1,158',
  '1',
  '432,657',
  '3,989',
  '57,261,822',
  '5,333,238',
  '10,736,784 ',
  'Europe',
  '',
  '22510',
  '',
  '',
  '108',
  ''],
 ['35',
  'Peru',
  '4,519,976',
  '',
  '222,161                                ',
  '',
  '4,296,857',
  '',
  '958',
  '4',
  '134,187',
  '6,595',
  '39,010,194',
  '1,158,115',
  '33,684,208 ',
  'South America',
  '',
  '71521',
  '',
  '',
  '28',
  ''],
 ['36',
  'Switzerland',
  '4,410,460',
  '',
  '14,452                                ',
  '',
  '4,393,587',
  '',
  '2,421',
  '39',
  '502,695',
  '1,647',
  '23,833,472',
  '2,716,487',
  '8,773,637 ',
  'Europe',
  '',
  '26070',
  '',
  '',
  '276',
  ''],
 ['37',
  'Philippines',
  '4,174,101',
  '',
  '66,643                                ',
  '',
  '4,103,828',
  '',
  '3,630',
  '162',
  '37,100',
  '592',
  '35,659,012',
  '316,944',
  '112,508,994 ',
  'Asia',
  '',
  '271,6883',
  '',
  '',
  '32',
  ''],
 ['38',
  'South Africa',
  '4,076,463',
  '',
  '102,595                                ',
  '',
  '3,912,506',
  '',
  '61,362',
  '192',
  '67,095',
  '1,689',
  '26,795,090',
  '441,027',
  '60,756,135 ',
  'Africa',
  '',
  '155922',
  '',
  '',
  '1,010',
  ''],
 ['39',
  'Romania',
  '3,421,949',
  '',
  '68,282                                ',
  '',
  '3,345,569',
  '',
  '8,098',
  '45',
  '179,806',
  '3,588',
  '27,864,101',
  '1,464,117',
  '19,031,335 ',
  'Europe',
  '',
  '62791',
  '',
  '',
  '426',
  ''],
 ['40',
  'Denmark',
  '3,183,596',
  '',
  '8,808                                ',
  '',
  '3,174,311',
  '',
  '477',
  '4',
  '545,608',
  '1,510',
  '129,330,859',
  '22,164,862',
  '5,834,950 ',
  'Europe',
  '',
  '26620',
  '',
  '',
  '82',
  ''],
 ['41',
  'Hong Kong',
  '2,918,626',
  '',
  '14,216                                ',
  '',
  '2,901,887',
  '+468',
  '2,523',
  '28',
  '383,813',
  '1,869',
  '76,127,725',
  '10,011,143',
  '7,604,299 ',
  'Asia',
  '',
  '35350',
  '',
  '',
  '332',
  ''],
 ['42',
  'Sweden',
  '2,715,584',
  '',
  '24,792                                ',
  '',
  '2,689,229',
  '+49',
  '1,563',
  '1',
  '265,739',
  '2,426',
  '19,500,873',
  '1,908,301',
  '10,218,971 ',
  'Europe',
  '',
  '44121',
  '',
  '',
  '153',
  ''],
 ['43',
  'Singapore',
  '2,555,733',
  '',
  '1,875                                ',
  '',
  '2,149,583',
  '',
  '404,275',
  '2',
  '430,001',
  '315',
  '24,756,666',
  '4,165,302',
  '5,943,546 ',
  'Asia',
  '',
  '23,1700',
  '',
  '',
  '68,019',
  ''],
 ['44',
  'Serbia',
  '2,544,952',
  '',
  '18,057                                ',
  '',
  '2,526,895',
  '',
  '0',
  '',
  '294,112',
  '2,087',
  '13,045,481',
  '1,507,622',
  '8,653,016 ',
  'Europe',
  '',
  '34791',
  '',
  '',
  '',
  ''],
 ['45',
  'Iraq',
  '2,465,545',
  '',
  '25,375                                ',
  '',
  '2,439,497',
  '',
  '673',
  '21',
  '58,474',
  '602',
  '19,544,451',
  '463,523',
  '42,164,965 ',
  'Asia',
  '',
  '171,6622',
  '',
  '',
  '16',
  ''],
 ['46',
  'New Zealand',
  '2,457,924',
  '',
  '4,746                                ',
  '',
  '2,451,017',
  '',
  '2,161',
  '',
  '501,801',
  '969',
  '7,768,604',
  '1,586,011',
  '4,898,203 ',
  'Australia/Oceania',
  '',
  '21,0321',
  '',
  '',
  '441',
  ''],
 ['47',
  'Hungary',
  '2,203,761',
  '',
  '48,881                                ',
  '',
  '2,152,155',
  '',
  '2,725',
  '2',
  '229,409',
  '5,088',
  '11,394,556',
  '1,186,160',
  '9,606,259 ',
  'Europe',
  '',
  '41971',
  '',
  '',
  '284',
  ''],
 ['48',
  'Bangladesh',
  '2,045,408',
  '',
  '29,477                                ',
  '',
  '1,998,448',
  '',
  '17,483',
  'N/A',
  '12,183',
  '176',
  '15,254,399',
  '90,862',
  '167,885,689 ',
  'Asia',
  '',
  '825,69511',
  '',
  '',
  '104',
  ''],
 ['49',
  'Slovakia',
  '1,867,076',
  '',
  '21,167                                ',
  '',
  '1,845,758',
  '',
  '151',
  '6',
  '341,943',
  '3,877',
  '7,434,889',
  '1,361,653',
  '5,460,193 ',
  'Europe',
  '',
  '32581',
  '',
  '',
  '28',
  ''],
 ['50',
  'Georgia',
  '1,855,289',
  '',
  '17,132                                ',
  '',
  '1,776,548',
  '',
  '61,609',
  '',
  '467,476',
  '4,317',
  '16,920,079',
  '4,263,340',
  '3,968,738 ',
  'Asia',
  '',
  '22320',
  '',
  '',
  '15,524',
  ''],
 ['51',
  'Jordan',
  '1,746,997',
  '',
  '14,122                                ',
  '',
  '1,731,007',
  '',
  '1,868',
  '59',
  '169,597',
  '1,371',
  '17,201,885',
  '1,669,945',
  '10,300,869 ',
  'Asia',
  '',
  '67291',
  '',
  '',
  '181',
  ''],
 ['52',
  'Ireland',
  '1,719,064',
  '',
  '9,200                                ',
  '',
  '1,706,408',
  '',
  '3,456',
  '19',
  '342,429',
  '1,833',
  '13,083,449',
  '2,606,161',
  '5,020,199 ',
  'Europe',
  '',
  '35460',
  '',
  '',
  '688',
  ''],
 ['53',
  'Pakistan',
  '1,581,698',
  '',
  '30,664                                ',
  '',
  '1,538,689',
  '',
  '12,345',
  '1',
  '6,892',
  '134',
  '30,580,695',
  '133,256',
  '229,488,994 ',
  'Asia',
  '',
  '1457,4848',
  '',
  '',
  '54',
  ''],
 ['54',
  'Norway',
  '1,487,386',
  '',
  '5,631                                ',
  '',
  '1,481,327',
  '',
  '428',
  '20',
  '269,876',
  '1,022',
  '11,002,430',
  '1,996,315',
  '5,511,370 ',
  'Europe',
  '',
  '49791',
  '',
  '',
  '78',
  ''],
 ['55',
  'Finland',
  '1,484,646',
  '',
  '10,185                                ',
  '',
  '1,473,703',
  '+37',
  '758',
  '21',
  '267,265',
  '1,833',
  '12,108,977',
  '2,179,850',
  '5,554,960 ',
  'Europe',
  '',
  '45450',
  '',
  '',
  '136',
  ''],
 ['56',
  'Kazakhstan',
  '1,411,831',
  '',
  '13,848                                ',
  '',
  '1,383,020',
  '',
  '14,963',
  '24',
  '73,514',
  '721',
  '11,575,012',
  '602,707',
  '19,205,043 ',
  'Asia',
  '',
  '141,3872',
  '',
  '',
  '779',
  ''],
 ['57',
  'Slovenia',
  '1,344,625',
  '',
  '7,100                                ',
  '',
  '1,337,079',
  '',
  '446',
  '8',
  '647,066',
  '3,417',
  '2,847,701',
  '1,370,382',
  '2,078,034 ',
  'Europe',
  '',
  '22931',
  '',
  '',
  '215',
  ''],
 ['58',
  'Lithuania',
  '1,324,271',
  '',
  '9,703                                ',
  '',
  '1,312,741',
  '',
  '1,827',
  '1',
  '497,527',
  '3,645',
  '10,479,496',
  '3,937,132',
  '2,661,708 ',
  'Europe',
  '',
  '22740',
  '',
  '',
  '686',
  ''],
 ['59',
  'Bulgaria',
  '1,311,330',
  '',
  '38,455                                ',
  '',
  '1,270,927',
  '',
  '1,948',
  '12',
  '191,586',
  '5,618',
  '11,340,562',
  '1,656,863',
  '6,844,597 ',
  'Europe',
  '',
  '51781',
  '',
  '',
  '285',
  ''],
 ['60',
  'Guatemala',
  '1,276,670',
  '',
  '20,257                                ',
  '',
  '1,255,151',
  '',
  '1,262',
  '5',
  '68,697',
  '1,090',
  '7,593,848',
  '408,622',
  '18,584,039 ',
  'North America',
  '',
  '159172',
  '',
  '',
  '68',
  ''],
 ['61',
  'Morocco',
  '1,275,864',
  '',
  '16,297                                ',
  '',
  '1,256,151',
  '',
  '3,416',
  '3',
  '33,777',
  '431',
  '13,001,033',
  '344,191',
  '37,772,756 ',
  'Africa',
  '',
  '302,3183',
  '',
  '',
  '90',
  ''],
 ['62',
  'Croatia',
  '1,274,603',
  '',
  '18,306                                ',
  '',
  '1,255,995',
  '',
  '302',
  '',
  '313,997',
  '4,510',
  '5,629,370',
  '1,386,788',
  '4,059,286 ',
  'Europe',
  '',
  '32221',
  '',
  '',
  '74',
  ''],
 ['63',
  'Costa Rica',
  '1,238,883',
  '',
  '9,428                                ',
  '',
  '860,711',
  '',
  '368,744',
  '52',
  '239,058',
  '1,819',
  '4,659,757',
  '899,158',
  '5,182,354 ',
  'North America',
  '',
  '45501',
  '',
  '',
  '71,154',
  ''],
 ['64',
  'Lebanon',
  '1,238,552',
  '',
  '10,936                                ',
  '',
  '1,087,587',
  '',
  '140,029',
  '74',
  '185,277',
  '1,636',
  '4,795,578',
  '717,380',
  '6,684,849 ',
  'Asia',
  '',
  '56111',
  '',
  '',
  '20,947',
  ''],
 ['65',
  'Bolivia',
  '1,207,206',
  '',
  '22,399                                ',
  '',
  '1,177,145',
  '',
  '7,662',
  '220',
  '100,662',
  '1,868',
  '2,710,261',
  '225,993',
  '11,992,656 ',
  'South America',
  '',
  '105354',
  '',
  '',
  '639',
  ''],
 ['66',
  'Tunisia',
  '1,153,361',
  '',
  '29,423                                ',
  '',
  'N/A',
  'N/A',
  'N/A',
  '44',
  '95,741',
  '2,442',
  '5,013,383',
  '416,164',
  '12,046,656 ',
  'Africa',
  '',
  '104092',
  '',
  '',
  '1,157',
  ''],
 ['67',
  'Cuba',
  '1,115,125',
  '',
  '8,530                                ',
  '',
  '1,106,533',
  '',
  '62',
  '2',
  '98,634',
  '754',
  '14,345,940',
  '1,268,918',
  '11,305,652 ',
  'North America',
  '',
  '101,3251',
  '',
  '',
  '5',
  ''],
 ['68',
  'Ecuador',
  '1,069,114',
  '',
  '36,042                                ',
  '',
  '1,033,072',
  '',
  '0',
  '759',
  '59,024',
  '1,990',
  '3,082,403',
  '170,173',
  '18,113,361 ',
  'South America',
  '',
  '175036',
  '',
  '',
  '',
  ''],
 ['69',
  'UAE',
  '1,067,030',
  '',
  '2,349                                ',
  '',
  '1,054,525',
  '',
  '10,156',
  '',
  '105,837',
  '233',
  '200,732,262',
  '19,910,389',
  '10,081,785 ',
  'Asia',
  '',
  '94,2920',
  '',
  '',
  '1,007',
  ''],
 ['70',
  'Panama',
  '1,048,045',
  '',
  '8,658                                ',
  '',
  '1,039,191',
  '',
  '196',
  '16',
  '235,677',
  '1,947',
  '7,792,123',
  '1,752,234',
  '4,446,964 ',
  'North America',
  '',
  '45141',
  '',
  '',
  '44',
  ''],
 ['71',
  'Uruguay',
  '1,038,774',
  '',
  '7,634                                ',
  '',
  '1,030,944',
  '',
  '196',
  '18',
  '297,131',
  '2,184',
  '6,114,822',
  '1,749,083',
  '3,496,016 ',
  'South America',
  '',
  '34581',
  '',
  '',
  '56',
  ''],
 ['72',
  'Mongolia',
  '1,010,975',
  '',
  '2,179                                ',
  '',
  '1,008,796',
  '',
  '0',
  '192',
  '299,275',
  '645',
  '4,030,048',
  '1,193,000',
  '3,378,078 ',
  'Asia',
  '',
  '31,5501',
  '',
  '',
  '',
  ''],
 ['73',
  'Nepal',
  '1,003,434',
  '',
  '12,031                                ',
  '',
  '991,322',
  '',
  '81',
  '',
  '33,198',
  '398',
  '6,047,766',
  '200,088',
  '30,225,582 ',
  'Asia',
  '',
  '302,5125',
  '',
  '',
  '3',
  ''],
 ['74',
  'Belarus',
  '994,037',
  '',
  '7,118                                ',
  '',
  '985,592',
  '',
  '1,327',
  '',
  '105,381',
  '755',
  '13,646,641',
  '1,446,722',
  '9,432,800 ',
  'Europe',
  '',
  '91,3251',
  '',
  '',
  '141',
  ''],
 ['75',
  'Latvia',
  '978,409',
  '',
  '6,392                                ',
  '',
  '971,406',
  '',
  '611',
  '',
  '529,202',
  '3,457',
  '7,880,260',
  '4,262,279',
  '1,848,837 ',
  'Europe',
  '',
  '22890',
  '',
  '',
  '330',
  ''],
 ['76',
  'Saudi Arabia',

In [ ]:
import csv
file = open('covid_data.csv','w')
x = csv.writer(file)
x.writerows(data)
file.close()

In [ ]:
import pandas as pd
df = pd.read_csv('covid_data.csv',encoding = 'latin1')
df

,#,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",...,Tests/,1M pop,Unnamed: 15,Population,Continent,1 Caseevery X ppl1 Deathevery X ppl1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop,Unnamed: 22
0,1,USA,"108,292,767",NaN,"1,174,578",NaN,"106,093,952",NaN,"1,024,237","1,362",...,"3,542,636","334,805,269",North America,NaN,32850,NaN,NaN,"3,059",NaN,NaN
1,2,India,"44,997,642",NaN,"531,930",NaN,"44,465,138",NaN,574,NaN,...,"661,721","1,406,631,776",Asia,NaN,"312,6442",NaN,NaN,0.4,NaN,NaN
2,3,France,"40,138,560",NaN,"167,642",NaN,"39,970,918",NaN,0,869,...,"4,139,547","65,584,518",Europe,NaN,23910,NaN,NaN,NaN,NaN,NaN
3,4,Germany,"38,428,685",NaN,"174,352",NaN,"38,240,600",NaN,"13,733",NaN,...,"1,458,359","83,883,596",Europe,NaN,24811,NaN,NaN,164,NaN,NaN
4,5,Brazil,"37,783,855",NaN,"705,313",NaN,"36,249,161",NaN,"829,381",NaN,...,"296,146","215,353,593",South America,NaN,63053,NaN,NaN,"3,851",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,227,Tokelau,80,NaN,,NaN,NaN,NaN,80,NaN,...,NaN,"1,378",Australia/Oceania,NaN,17,NaN,NaN,"58,055",NaN,NaN
227,228,Vatican City,29,NaN,,NaN,29,NaN,0,NaN,...,NaN,799,Europe,NaN,28,NaN,NaN,NaN,NaN,NaN
228,229,Western Sahara,10,NaN,1,NaN,9,NaN,0,NaN,...,NaN,"626,161",Africa,NaN,"62,616626,161",NaN,NaN,NaN,NaN,NaN
229,230,MS Zaandam,9,NaN,2,NaN,7,NaN,0,NaN,...,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
230,231,China,"503,302",NaN,"5,272",NaN,"379,053",NaN,"118,977",NaN,...,"110,461","1,448,471,400",Asia,NaN,"2,878274,7489",NaN,NaN,82,NaN,NaN

In [ ]:
countries = list(df['Country,Other'])
total_cases = df['TotalCases']
total_cases = list(map(lambda x:int(x.replace(',' , '')),list(df['TotalCases'] )))

In [ ]:
#   !pip install plotly==5.14.1

import plotly.graph_objects as go

fig = go.Figure([go.Bar(x=countries[0:10], y=total_cases[0:10])])
fig.show()